name: Generate CycloneDX SBOM

on:
  push:
    branches:
      - main  # Adjust this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Adjust to your desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Generate CycloneDX SBOM
        uses: CycloneDX/gh-node-module-generatebom@v1
        with:
          path: './'  # Path to your Node.js project (adjust as needed)
          output: './bom.xml'  # Output filename (adjust as needed)
